### ISSUE TITLE
Add tests on orchestration script

### ISSUE THREAD

**Issue by Silas-Asamoah** [dzeble/MLOps_Project#3]
I made a list of tests with ChatGPT that I want you to use to make different PRs

1. **Issue: Add Unit Tests for Data Reading Function**
   - Description: Create unit tests for `read_dafaframe` to ensure it correctly reads and processes the CSV files. Test cases should include checking the handling of different data formats, missing values, and the correct application of label and one-hot encoding.

2. **Issue: Add Tests for Data Transformation Logic**
   - Description: Implement tests for the `transform` function to validate that the train and validation datasets are correctly split and that the target variable is separated from the features.

3. **Issue: Test Training Function for Model Accuracy**
   - Description: Develop tests for the `training` function to ensure the model trains correctly. This includes verifying if the ExtraTreesClassifier is instantiated with the right parameters and if the model performance metrics (RMSE, accuracy) are within acceptable ranges.

4. **Issue: Validate MLflow Integration**
   - Description: Write tests to confirm that MLflow correctly logs parameters, metrics, and artifacts. Ensure that the MLflow experiment is set up properly and that all relevant data is being logged.

5. **Issue: Integration Testing for the End-to-End Workflow**
   - Description: Set up an integration test for the `main_flow` function to ensure the entire pipeline from data loading, processing, training, to logging works seamlessly. This test should mimic a real-world scenario as closely as possible.

6. **Issue: Test for Handling Incorrect File Paths**
   - Description: Add tests to verify the behavior of the script when given incorrect file paths for training and validation data. The system should handle such errors gracefully.

7. **Issue: Check for Overfitting in Model Training**
   - Description: Implement tests to detect overfitting in the ExtraTreesClassifier model. This could involve comparing training and validation performance metrics.

8. **Issue: Test Environment Variable Dependency**
   - Description: Since the script depends on environment variables, create tests to ensure that the script behaves as expected when these variables are missing or incorrectly set.

These issues aim to cover a comprehensive range of tests and improvements, ensuring the robustness and reliability of the ML pipeline.

**Comment by dzeble** [comment]
Done
